[package]
name = "royce-mathew/topbarpp"
description = "Construct dynamic and intuitive topbar icons. Enhance the appearance and behaviour of these icons with features such as themes, dropdowns and menus."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "2.9.41"
exclude = [
	".github",
    ".vscode",
	"docs",
	"site",
	".gitattributes",
	".gitignore",
	"aftman.toml",
	"foreman.toml",
	"LICENSE",
	"mkdocs.yml",
    "sourcemap.json",
	"README.md",
]